#!/bin/bash
# OB-LA-DI Compiler Script 

if [ "$#" != "1" ]
then
	
	echo -e "\033[0;31mERROR - MISSING SOURCE FILE PATH \033[0m"

else

	java -jar "/usr/local/bin/ob-la-di.jar" "$1"
	
	filename=$1
	filename=${filename##*/}
	filename=${filename%.*}

	if [ -e "$HOME/$filename.asm" ]
	then

		cd $HOME && nasm -f macho64 -g $filename.asm 
				 && ld -macosx_version_min 10.7.0 -lSystem -o $filename $filename.o 
				 && ./$filename
				 
		rm "$HOME/$filename.asm"
		rm "$HOME/$filename.o"
	fi
fi