<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>obl</string>
		<string>inc</string>
	</array>
	<key>name</key>
	<string>OB-LA-DI</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(LET|VAR|INT|IF|ELSE|WHILE|PRINT|PRINTLN|INPUT|OR|AND|let|var|int|if|else|while|print|println|input|or|and)\b</string>
			<key>name</key>
			<string>keyword.control.obl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\x24)\b</string>
			<key>name</key>
			<string>keyword.control.obl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>variable.parameter.register.obl</string>
		</dict>
		<dict>
			<key>match</key>
			<string></string>
			<key>name</key>
			<string>variable.parameter.register.obl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.character.decimal.obl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(").*?(")</string>
			<key>name</key>
			<string>string.obl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>#</string>
			<key>name</key>
			<string>comment.obl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(,|\[|\]|\+|\-|\*|\/|=|\x3C|\x3E|\{|\})</string>
			<key>name</key>
			<string>source.obl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>.+?</string>
			<key>name</key>
			<string>entity.name.function.obl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.obl</string>
	<key>uuid</key>
	<string>32257fc7-0688-47c7-9540-f4c2d7affea4</string>
</dict>
</plist>
